version: '2'
services:
  product:
    image: java:8
    working_dir: /app
    volumes:
        - ./core/vis-productservice/target:/app
    command: java -jar /app/product-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
  category:
    image: java:8
    working_dir: /app
    volumes:
        - ./core/vis-categoryservice/target:/app
    command: java -jar /app/category-0.0.1-SNAPSHOT.jar
    ports:
      - "8081:8081"
  user:
    image: java:8
    working_dir: /app
    volumes:
        - ./core/vis-userservice/target:/app
    command: java -jar /app/userservice-1.0-SNAPSHOT.jar
    ports:
      - "8082:8082"
  productcategory:
    image: java:8
    working_dir: /app
    volumes:
        - ./composite/vis-productcategoryservice/target:/app
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1090 -jar /app/productandcategoryservice-0.0.1-SNAPSHOT.jar
    ports:
      - "8090:8090"
      - "1090:1090"
  eureka:
    image: java:8
    working_dir: /app
    volumes:
        - ./infrastructure/vis-eureka/target:/app
    command: java -jar /app/eureka-server-0.0.1-SNAPSHOT.jar
    ports:
      - "8761:8761"
  zuul:
    image: java:8
    working_dir: /app
    volumes:
        - ./infrastructure/vis-zuul/target:/app
    command: java -jar /app/zuul-server-0.0.1-SNAPSHOT.jar
    ports:
      - "8762:8762"
  authserver:
    image: java:8
    working_dir: /app
    volumes:
        - ./infrastructure/vis-authserver/target:/app
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1063 -jar /app/hello-oauth-srv-1.0-SNAPSHOT.jar
    ports:
      - "8763:8763"
      - "1063:1063"
  frontend:
    image: tomcat:latest
    volumes:
        - ./frontend/vis-client/target/EShop-1.0.0.war:/usr/local/tomcat/webapps/EShop.war
        - ./frontend/vis-client/target/EShop-1.0.0.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - "8000:8080"